import {readJson,writeJson,analyticsDayPath} from './storage.mjs';
function dayKey(d=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);}
function cleanQuery(q){return String(q||'').trim().replace(/\s+/g,' ').slice(0,100);}
export async function logSearch(q,total){
 const query=cleanQuery(q);if(!query)return;const now=new Date(),day=dayKey(now),path=analyticsDayPath(day);
 try{const doc=await readJson(path,{day,updatedAt:null,queries:{}},{ttlMs:0});const k=query.toLowerCase(),prev=doc.queries?.[k]||{query,count:0,zeroCount:0,totalResultSum:0,lastTotal:0};doc.queries={...(doc.queries||{}),[k]:{query:prev.query||query,count:Number(prev.count||0)+1,zeroCount:Number(prev.zeroCount||0)+(Number(total||0)===0?1:0),totalResultSum:Number(prev.totalResultSum||0)+Number(total||0),lastTotal:Number(total||0),lastAt:now.toISOString()}};doc.updatedAt=now.toISOString();await writeJson(path,doc);}catch{}
}
function datesBetween(start,end){const out=[],a=new Date(start+'T00:00:00Z'),b=new Date(end+'T00:00:00Z');for(let d=new Date(a);d<=b&&out.length<366;d.setUTCDate(d.getUTCDate()+1))out.push(d.toISOString().slice(0,10));return out;}
export async function readAnalyticsRange(start,end){const out=new Map(),paths=datesBetween(start,end).map(analyticsDayPath);const docs=await Promise.all(paths.map(p=>readJson(p,null,{ttlMs:30*1000})));for(const doc of docs){for(const v of Object.values(doc?.queries||{})){const k=String(v.query||'').toLowerCase(),x=out.get(k)||{query:v.query||k,count:0,zeroCount:0,totalResultSum:0,lastTotal:0,lastAt:null};x.count+=Number(v.count||0);x.zeroCount+=Number(v.zeroCount||0);x.totalResultSum+=Number(v.totalResultSum||0);if(!x.lastAt||String(v.lastAt||'')>x.lastAt){x.lastAt=v.lastAt||null;x.lastTotal=Number(v.lastTotal||0);}out.set(k,x);}}return [...out.values()].map(x=>({...x,avgResults:x.count?Math.round((x.totalResultSum/x.count)*10)/10:0})).sort((a,b)=>b.count-a.count||String(b.lastAt||'').localeCompare(String(a.lastAt||'')));}
export async function readAnalytics(days=30){const end=dayKey(),d=new Date();d.setDate(d.getDate()-(days-1));return readAnalyticsRange(dayKey(d),end);}
export {dayKey};
