import * as XLSX from 'xlsx';
import {readJson,writeJson,PATHS,chunkPath} from '../storage.mjs';
import {requireAdmin} from '../admin-auth.mjs';
import {addHistory} from '../history.mjs';
const EMPTY={lists:[]};
const s=x=>String(x??'').trim();
const norm=x=>s(x).normalize('NFKC').toLowerCase().replace(/[\s\p{P}\p{S}]/gu,'');
const isbn=x=>s(x).replace(/[^0-9Xx]/g,'').toUpperCase();
const dateOk=x=>!x||/^\d{4}-\d{2}-\d{2}$/.test(x);
const visible=l=>l.active&&(!l.startDate||new Date().toISOString().slice(0,10)>=l.startDate)&&(!l.endDate||new Date().toISOString().slice(0,10)<=l.endDate);
const pub=r=>({id:r.id,chunk:r.chunk,title:r.title,author:r.author,publisher:r.publisher,isbn13:r.isbn13,callNumbers:r.callNumbers||[],locations:r.locations||[],copies:r.copies||0,cover:r.cover||'',introPreview:r.introPreview||'',topics:r.primaryTopics||r.topics||[]});
function match(item,records){const i=isbn(item.isbn),t=norm(item.title),a=norm(item.author),p=norm(item.publisher);let hits=[];
 if(i.length>=10)hits=records.filter(r=>isbn(r.isbn13)===i);
 if(!hits.length&&t&&a){const candidates=records.filter(r=>norm(r.title)===t&&norm(r.author)===a&&(!p||!norm(r.publisher)||norm(r.publisher)===p));if(i&&candidates.some(r=>isbn(r.isbn13)&&isbn(r.isbn13)!==i))return {status:'확인 필요',reason:'다른 ISBN 또는 판본',books:[]};hits=candidates;}
 // Conflicting ISBN/edition or ambiguous title-only matches are never auto-linked.
 if(hits.length&&hits.some(r=>t&&norm(r.title)!==t||a&&norm(r.author)!==a||p&&norm(r.publisher)&&norm(r.publisher)!==p))return {status:'확인 필요',reason:'ISBN 또는 서지정보 충돌',books:[]};
 if(!hits.length)return {status:'입고 예정',reason:'소장자료 미확인',books:[]};
 const unique=[...new Map(hits.map(r=>[r.id,r])).values()];
 if(unique.length>1&&new Set(unique.map(r=>isbn(r.isbn13)||norm(r.title)+'|'+norm(r.author))).size>1)return {status:'확인 필요',reason:'서로 다른 판본 확인 필요',books:[]};
 return {status:'소장 중',reason:'소장정보 연결',books:unique.map(pub)};
}
function clipRaw(v,n=3000){return s(v).replace(/<br\s*\/?>/gi,'\n').replace(/<\/p>/gi,'\n').replace(/<[^>]*>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/\s+/g,' ').slice(0,n);}
function verified(item,record){const a=norm(item.title),b=norm(record.title);if(a&&b&&a!==b)return false;const ia=isbn(item.isbn),ib=isbn(record.isbn13);return !!(ia&&ib&&ia===ib);}
async function savedMetadata(item){const idx=await readJson(PATHS.searchIndex,null);const matches=(idx?.records||[]).filter(r=>verified(item,r));for(const r of matches){if(!Number.isInteger(Number(r.chunk)))continue;const chunk=await readJson(chunkPath(Number(r.chunk)),null);const m=chunk?.records?.find(x=>x.id===r.id);if(m?.yes24&&(m.yes24.cover||m.yes24.introduction||m.yes24.toc))return m.yes24;}return null;}
async function externalMetadata(item){const key=process.env.YES24_API_KEY;if(!key||isbn(item.isbn).length!==13)return null;const u=new URL('https://apis.yes24.com/v1/goods/itemDetail');u.searchParams.set('searchType','ISBN13');u.searchParams.set('query',item.isbn);u.searchParams.set('detail','Y');try{const r=await fetch(u,{headers:{'X-Api-Key':key,Accept:'application/json'},cache:'no-store'});if(!r.ok)return null;const x=(await r.json())?.data?.items?.[0];if(!x||isbn(x.isbn13)!==isbn(item.isbn)||norm(x.title)!==norm(item.title))return null;return {cover:x.cover||'',introduction:clipRaw(x.contentDetail?.bookIntroduction||'',2400),toc:clipRaw(x.contentDetail?.tableOfContents||'',8000)};}catch{return null;}}
async function bodyBuffer(req){if(Buffer.isBuffer(req.body))return req.body;if(req.body instanceof Uint8Array)return Buffer.from(req.body);if(typeof req.body==='string')return Buffer.from(req.body,'binary');const chunks=[];for await(const c of req)chunks.push(Buffer.isBuffer(c)?c:Buffer.from(c));return Buffer.concat(chunks);}
function hash(v){let h=2166136261;for(const c of v){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
function template(){const w=XLSX.utils.book_new();XLSX.utils.book_append_sheet(w,XLSX.utils.json_to_sheet([{'도서명':'예시 도서','저자':'예시 저자','출판사':'예시 출판사','ISBN':'9781234567897','주제':'한국소설','책소개':'','표지URL':''}]),'신간도서');return XLSX.write(w,{type:'buffer',bookType:'xlsx'});}
function parse(buf){const w=XLSX.read(buf,{type:'buffer'}),rows=XLSX.utils.sheet_to_json(w.Sheets[w.SheetNames[0]],{defval:'',raw:false});if(rows.length&&!Object.keys(rows[0]).some(k=>['도서명','자료명','서명'].includes(k)))throw Error('도서명 열이 필요합니다.');const seen=new Set();return rows.map((r,i)=>({id:`new_${i+1}`,title:s(r['도서명']||r['자료명']||r['서명']),author:s(r['저자']),publisher:s(r['출판사']),isbn:isbn(r['ISBN']||r['ISBN13']),topic:s(r['주제']),intro:s(r['책소개']),cover:/^https:\/\//.test(s(r['표지URL']))?s(r['표지URL']):''})).filter(x=>{if(!x.title)return false;const key=x.isbn||norm(x.title)+'|'+norm(x.author);if(seen.has(key))return false;seen.add(key);return true;});}
export default async function handler(req,res){try{const mode=s(req.query?.mode),action=s(req.query?.action),doc=await readJson(PATHS.newBooks,EMPTY,{ttlMs:req.method==='GET'&&mode!=='admin'?30000:0});doc.lists=doc.lists||[];
 if(req.method==='GET'&&['home','list'].includes(mode)){const lists=doc.lists.filter(visible).sort((a,b)=>(a.displayOrder||999)-(b.displayOrder||999));const result=mode==='list'?lists.filter(l=>l.id===s(req.query.id)):lists;res.setHeader('Cache-Control','no-store');return res.status(200).json({ok:true,lists:mode==='home'?result.map(l=>({...l,items:l.items.map((x,i)=>({...x,sourceIndex:i})).sort((a,b)=>hash(s(req.query.seed||'')+'|'+a.id)-hash(s(req.query.seed||'')+'|'+b.id)).slice(0,10),hasMore:l.items.length>10,totalItems:l.items.length})):result});}
 if(!requireAdmin(req,res))return;
 if(req.method==='GET'&&mode==='admin')return res.status(200).json({ok:true,lists:doc.lists});
 if(req.method==='GET'&&mode==='template'){res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');return res.status(200).send(template());}
 if(req.method!=='POST')return res.status(405).json({ok:false,message:'지원하지 않는 요청'});
 const body=typeof req.body==='object'&&!Buffer.isBuffer(req.body)?req.body:{};
 if(action==='save'){const at=doc.lists.findIndex(l=>l.id===s(body.id));if(!s(body.name)||!dateOk(body.startDate)||!dateOk(body.endDate)||body.startDate&&body.endDate&&body.startDate>body.endDate)return res.status(400).json({ok:false,message:'목록명과 공개기간을 확인해 주세요.'});const old=at<0?{}:doc.lists[at],l={...old,id:old.id||`newlist_${Date.now().toString(36)}`,name:s(body.name).slice(0,100),description:s(body.description).slice(0,400),startDate:s(body.startDate),endDate:s(body.endDate),active:!!body.active,displayOrder:old.displayOrder||doc.lists.length+1,items:old.items||[]};if(at<0)doc.lists.push(l);else doc.lists[at]=l;await writeJson(PATHS.newBooks,doc);await addHistory('new-books','신간 홍보목록 저장',{name:l.name});return res.status(200).json({ok:true,list:l});}
 if(action==='upload'){const at=doc.lists.findIndex(l=>l.id===s(req.query.id));if(at<0)return res.status(404).json({ok:false,message:'먼저 홍보목록을 저장하세요.'});const buf=await bodyBuffer(req);if(buf.length>3_000_000)return res.status(400).json({ok:false,message:'3MB 이하 엑셀만 업로드할 수 있습니다.'});const items=parse(buf);if(!items.length)return res.status(400).json({ok:false,message:'유효한 도서가 없습니다.'});doc.lists[at].items=items.map(x=>({...x,status:'입고 예정',books:[]}));await writeJson(PATHS.newBooks,doc);await addHistory('new-books','신간 홍보목록 업로드',{count:items.length});return res.status(200).json({ok:true,total:items.length});}
 if(action==='enrich'){const at=doc.lists.findIndex(l=>l.id===s(body.id));if(at<0)return res.status(404).json({ok:false,message:'홍보목록을 찾지 못했습니다.'});const items=doc.lists[at].items||[];const offset=Math.max(0,Number(body.offset)||0),limit=5;let updated=0,unavailable=0;for(let n=offset;n<Math.min(items.length,offset+limit);n++){const item=items[n];if(!item.isbn||item.cover&&item.intro&&item.toc){continue;}const meta=await savedMetadata(item)||await externalMetadata(item);if(!meta){unavailable++;continue;}if(!item.cover&&/^https:\/\//.test(s(meta.cover)))item.cover=meta.cover;if(!item.intro)item.intro=clipRaw(meta.introduction||'',2400);if(!item.toc)item.toc=clipRaw(meta.toc||'',8000);if(item.cover||item.intro||item.toc)updated++;}await writeJson(PATHS.newBooks,doc);return res.status(200).json({ok:true,updated,unavailable,nextOffset:Math.min(items.length,offset+limit),total:items.length});}
 if(action==='preview-link'||action==='link'){const at=doc.lists.findIndex(l=>l.id===s(body.id));if(at<0)return res.status(404).json({ok:false,message:'홍보목록을 찾지 못했습니다.'});const idx=await readJson(PATHS.searchIndex,null);if(!Array.isArray(idx?.records))return res.status(409).json({ok:false,message:'검색 인덱스가 준비되지 않았습니다. 장서 데이터 갱신 후 검색 인덱스를 구축해 주세요.'});const matches=doc.lists[at].items.map(x=>({...x,...match(x,idx.records)}));const counts={owned:matches.filter(x=>x.status==='소장 중').length,pending:matches.filter(x=>x.status==='입고 예정').length,review:matches.filter(x=>x.status==='확인 필요').length};if(action==='link'){doc.lists[at].items=matches;await writeJson(PATHS.newBooks,doc);await addHistory('new-books','신간 홍보목록 소장정보 연동',counts);}return res.status(200).json({ok:true,counts,items:action==='preview-link'?matches:undefined});}
 if(action==='reorder'){const at=doc.lists.findIndex(l=>l.id===s(body.id)),to=at+(body.direction==='up'?-1:1);if(at<0||to<0||to>=doc.lists.length)return res.status(400).json({ok:false,message:'이동할 수 없습니다.'});[doc.lists[at],doc.lists[to]]=[doc.lists[to],doc.lists[at]];doc.lists.forEach((l,i)=>l.displayOrder=i+1);await writeJson(PATHS.newBooks,doc);return res.status(200).json({ok:true});}
 if(action==='delete'){doc.lists=doc.lists.filter(l=>l.id!==s(body.id));await writeJson(PATHS.newBooks,doc);return res.status(200).json({ok:true});}
 return res.status(400).json({ok:false,message:'알 수 없는 작업'});
 }catch(e){return res.status(500).json({ok:false,message:s(e.message)});}}
